# Generated by Django 4.2.13 on 2024-07-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0003_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="amount",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="стоимость курса"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="amount",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="стоимость курса"
            ),
        ),
    ]
