# Generated by Django 4.2.13 on 2024-07-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0004_course_amount_lesson_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="amount",
        ),
        migrations.AddField(
            model_name="course",
            name="last_update",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Последнее обновление"
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="status",
            field=models.BooleanField(
                blank=True, default=True, null=True, verbose_name="Cтатус подписки"
            ),
        ),
    ]
